import type { SquareType } from "./Square/Square.types";

export const BASE_PIECE_TYPES = {
  BISHOP: "bishop",
  KING: "king",
  KNIGHT: "knight",
  PAWN: "pawn",
  QUEEN: "queen",
  ROOK: "rook",
} as const;

export const FILE_IDS = [..."ABCDEFGH"] as const;

export const KNIGHT_INDEX_CHANGES = [
  [-1, -2],
  [-1, 2],
  [-2, -1],
  [-2, 1],
  [1, -2],
  [1, 2],
  [2, -1],
  [2, 1],
];

export const LABEL_TYPES = {
  FILE: "file",
  RANK: "rank",
} as const;

export const PLAYERS = {
  BLACK: "black",
  WHITE: "white",
} as const;

export const RANK_IDS = [..."87654321"] as const;

export const PIECE_TYPES = {
  BLACK_BISHOP: `${PLAYERS.BLACK}-${BASE_PIECE_TYPES.BISHOP}`,
  BLACK_KING: `${PLAYERS.BLACK}-${BASE_PIECE_TYPES.KING}`,
  BLACK_KNIGHT: `${PLAYERS.BLACK}-${BASE_PIECE_TYPES.KNIGHT}`,
  BLACK_PAWN: `${PLAYERS.BLACK}-${BASE_PIECE_TYPES.PAWN}`,
  BLACK_QUEEN: `${PLAYERS.BLACK}-${BASE_PIECE_TYPES.QUEEN}`,
  BLACK_ROOK: `${PLAYERS.BLACK}-${BASE_PIECE_TYPES.ROOK}`,
  WHITE_BISHOP: `${PLAYERS.WHITE}-${BASE_PIECE_TYPES.BISHOP}`,
  WHITE_KING: `${PLAYERS.WHITE}-${BASE_PIECE_TYPES.KING}`,
  WHITE_KNIGHT: `${PLAYERS.WHITE}-${BASE_PIECE_TYPES.KNIGHT}`,
  WHITE_PAWN: `${PLAYERS.WHITE}-${BASE_PIECE_TYPES.PAWN}`,
  WHITE_QUEEN: `${PLAYERS.WHITE}-${BASE_PIECE_TYPES.QUEEN}`,
  WHITE_ROOK: `${PLAYERS.WHITE}-${BASE_PIECE_TYPES.ROOK}`,
} as const;

export const DEFAULT_CONFIGURATION = {
  A1: PIECE_TYPES.WHITE_ROOK,
  A2: PIECE_TYPES.WHITE_PAWN,
  A7: PIECE_TYPES.BLACK_PAWN,
  A8: PIECE_TYPES.BLACK_ROOK,
  B1: PIECE_TYPES.WHITE_KNIGHT,
  B2: PIECE_TYPES.WHITE_PAWN,
  B7: PIECE_TYPES.BLACK_PAWN,
  B8: PIECE_TYPES.BLACK_KNIGHT,
  C1: PIECE_TYPES.WHITE_BISHOP,
  C2: PIECE_TYPES.WHITE_PAWN,
  C7: PIECE_TYPES.BLACK_PAWN,
  C8: PIECE_TYPES.BLACK_BISHOP,
  D1: PIECE_TYPES.WHITE_QUEEN,
  D2: PIECE_TYPES.WHITE_PAWN,
  D7: PIECE_TYPES.BLACK_PAWN,
  D8: PIECE_TYPES.BLACK_QUEEN,
  E1: PIECE_TYPES.WHITE_KING,
  E2: PIECE_TYPES.WHITE_PAWN,
  E7: PIECE_TYPES.BLACK_PAWN,
  E8: PIECE_TYPES.BLACK_KING,
  F1: PIECE_TYPES.WHITE_BISHOP,
  F2: PIECE_TYPES.WHITE_PAWN,
  F7: PIECE_TYPES.BLACK_PAWN,
  F8: PIECE_TYPES.BLACK_BISHOP,
  G1: PIECE_TYPES.WHITE_KNIGHT,
  G2: PIECE_TYPES.WHITE_PAWN,
  G7: PIECE_TYPES.BLACK_PAWN,
  G8: PIECE_TYPES.BLACK_KNIGHT,
  H1: PIECE_TYPES.WHITE_ROOK,
  H2: PIECE_TYPES.WHITE_PAWN,
  H7: PIECE_TYPES.BLACK_PAWN,
  H8: PIECE_TYPES.BLACK_ROOK,
};

export const DEFAULT_SQUARE_PROPS = RANK_IDS.reduce(
  (ids, rankId) => [
    ...ids,
    ...FILE_IDS.map((fileId) => ({
      squareId: `${fileId}${rankId}`,
      targets: [],
    })),
  ],
  [] as SquareType[],
);
