import { PIECE_TYPES } from "../../Board.constants";

export const PIECE_SYMBOLS = {
  [PIECE_TYPES.BLACK_BISHOP]: "♝",
  [PIECE_TYPES.BLACK_KING]: "♚",
  [PIECE_TYPES.BLACK_KNIGHT]: "♞",
  [PIECE_TYPES.BLACK_PAWN]: "♟",
  [PIECE_TYPES.BLACK_QUEEN]: "♛",
  [PIECE_TYPES.BLACK_ROOK]: "♜",
  [PIECE_TYPES.WHITE_BISHOP]: "♗",
  [PIECE_TYPES.WHITE_KING]: "♔",
  [PIECE_TYPES.WHITE_KNIGHT]: "♘",
  [PIECE_TYPES.WHITE_PAWN]: "♙",
  [PIECE_TYPES.WHITE_QUEEN]: "♕",
  [PIECE_TYPES.WHITE_ROOK]: "♖",
} as const;
